var allIcons = [
  "accessibility",
  "account-child",
  "account-circle",
  "airplanemode-on",
  "arrow-back",
  "arrow_down",
  "arrow_up",
  "autorenew",
  "av-timer",
  "bug-report",
  "cached",
  "call-split",
  "call",
  "cart",
  "checkbox-blank",
  "checkbox-marked",
  "close",
  "cloud",
  "color-lens",
  "credit-card",
  "devices",
  "directions-car",
  "directions-subway",
  "done",
  "email",
  "event",
  "facebook",
  "favorite",
  "flag",
  "folder",
  "get-app",
  "github",
  "golang",
  "google",
  "grade",
  "group-add",
  "home",
  "inbox",
  "keyboard-arrow-down",
  "keyboard-arrow-left",
  "keyboard-arrow-right",
  "keyboard-arrow-up",
  "label",
  "layers",
  "local-bar",
  "local-offer",
  "location-on",
  "lock",
  "map",
  "menu-down",
  "menu",
  "more-horiz",
  "more-vert",
  "navigate_after",
  "navigate_before",
  "nodejs",
  "notifications-none",
  "notifications",
  "person-add",
  "phone-android",
  "play-arrow",
  "playlist-add",
  "plus",
  "publ",
  "python",
  "query-builder",
  "question-answer",
  "room",
  "ruby",
  "school",
  "search",
  "settings-backup-restore",
  "share",
  "shopping-cart",
  "sync",
  "sync-problem",
  "system-update-tv",
  "terminal",
  "theaters",
  "twitter",
  "unfold-less",
  "unfold-more",
  "videocam",
  "view-module",
  "view-stream",
  "vpn-key",
  "warning",
  "webhooks",
  "whatshot",
  "work",
];

var iconPickerIcons = [
  "accessibility",
  "account-child",
  "airplanemode-on",
  "autorenew",
  "bug-report",
  "call",
  "cloud",
  "color-lens",
  "credit-card",
  "devices",
  "directions-car",
  "directions-subway",
  "email",
  "event",
  "favorite",
  "flag",
  "folder",
  "get-app",
  "grade",
  "home",
  "inbox",
  "label",
  "layers",
  "local-bar",
  "local-offer",
  "lock",
  "map",
  "phone-android",
  "publ",
  "query-builder",
  "question-answer",
  "room",
  "school",
  "share",
  "shopping-cart",
  "theaters",
  "videocam",
  "vpn-key",
  "whatshot",
  "work",
];

var IconStore = {

  getAllIcons: function() {
    return allIcons;
  },

  getIconPickerIcons: function() {
    return iconPickerIcons;
  },

  contains: function(string) {
    return allIcons.indexOf(string) !== -1;
  },

};

module.exports = IconStore;